spring.application.name=payment-system-spring

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/n11bootcamp}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8080